// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $MouseFollower from "./islands/MouseFollower.tsx";
import * as $ThemeController from "./islands/ThemeController.tsx";
import * as $about_me_ExpertiseCard from "./islands/about-me/ExpertiseCard.tsx";
import * as $about_me_SkillBadge from "./islands/about-me/SkillBadge.tsx";
import * as $about_me_StatCard from "./islands/about-me/StatCard.tsx";
import * as $about_me_Tabs from "./islands/about-me/Tabs.tsx";
import * as $hero_Buttons from "./islands/hero/Buttons.tsx";
import * as $hero_Content from "./islands/hero/Content.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Header.tsx": $Header,
    "./islands/MouseFollower.tsx": $MouseFollower,
    "./islands/ThemeController.tsx": $ThemeController,
    "./islands/about-me/ExpertiseCard.tsx": $about_me_ExpertiseCard,
    "./islands/about-me/SkillBadge.tsx": $about_me_SkillBadge,
    "./islands/about-me/StatCard.tsx": $about_me_StatCard,
    "./islands/about-me/Tabs.tsx": $about_me_Tabs,
    "./islands/hero/Buttons.tsx": $hero_Buttons,
    "./islands/hero/Content.tsx": $hero_Content,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
